# Generated by Django 5.0.1 on 2024-01-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Divar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("construction_year", models.IntegerField()),
                ("rooms", models.IntegerField()),
                ("total_price", models.CharField(max_length=100)),
                ("floor", models.IntegerField()),
                ("elevator", models.CharField(max_length=100)),
                ("parking", models.CharField(max_length=100)),
                ("warehouse", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=100)),
            ],
        ),
    ]
