# Generated by Django 5.0.1 on 2024-01-10 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("JabamaApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jabama",
            name="image_lint",
        ),
    ]
